
//----------------------------------------------------
// The following code was generated by CUP v0.11b ${cupversion} (SVN rev )
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 29;
  public static final int DIVIDE = 34;
  public static final int EQUALS = 38;
  public static final int GREATER = 41;
  public static final int LPAREN = 21;
  public static final int REPEAT = 13;
  public static final int FONTCOLOR = 18;
  public static final int INT = 2;
  public static final int PRINTLN = 28;
  public static final int LESS = 40;
  public static final int MINUS = 32;
  public static final int WRITE = 26;
  public static final int RPAREN = 22;
  public static final int AND = 36;
  public static final int NOT = 35;
  public static final int SEMICOLON = 23;
  public static final int OR = 37;
  public static final int BOOL = 3;
  public static final int COMMA = 24;
  public static final int PLUS = 31;
  public static final int ASSIGN = 44;
  public static final int LESSEQ = 42;
  public static final int IF = 10;
  public static final int DOT = 25;
  public static final int ID = 15;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 30;
  public static final int RETURN = 14;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int LCURLY = 19;
  public static final int CIN = 8;
  public static final int VOID = 4;
  public static final int RCURLY = 20;
  public static final int INTLITERAL = 16;
  public static final int TIMES = 33;
  public static final int ELSE = 11;
  public static final int COUT = 9;
  public static final int READ = 27;
  public static final int NOTEQUALS = 39;
  public static final int WHILE = 12;
  public static final int GREATEREQ = 43;
  public static final int STRINGLITERAL = 17;
  public static final int FALSE = 6;
  public static final int STRUCT = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "BOOL",
  "VOID",
  "TRUE",
  "FALSE",
  "STRUCT",
  "CIN",
  "COUT",
  "IF",
  "ELSE",
  "WHILE",
  "REPEAT",
  "RETURN",
  "ID",
  "INTLITERAL",
  "STRINGLITERAL",
  "FONTCOLOR",
  "LCURLY",
  "RCURLY",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "WRITE",
  "READ",
  "PRINTLN",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "NOT",
  "AND",
  "OR",
  "EQUALS",
  "NOTEQUALS",
  "LESS",
  "GREATER",
  "LESSEQ",
  "GREATEREQ",
  "ASSIGN"
  };
}

